spring:
  application:
    name: cosmo-cats-market
  liquibase:
    change-log: classpath:liquibase/changelog.yaml
    enabled: true

feature:
  cosmoCats:
    enabled: true
  kittyProducts:
    enabled: false